version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: multitenant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d multitenant_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  web:
    build: .
    command: |
      sh -c "
        echo 'Waiting for database...' &&
        python manage.py migrate_schemas --shared &&
        python manage.py migrate_schemas &&
        echo 'Starting Django server...' &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=True
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data: