# Generated by Django 4.2 on 2025-08-10 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('sample_type', models.CharField(max_length=100)),
                ('collection_date', models.DateTimeField()),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='collected', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('result_value', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.sample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
